baseURL: "https://example.com"  # 替换为您的域名
title: "我的博客"
theme: PaperMod
pagination:
  pageSize: 5  # 使用与之前 paginate 相同的数值


# 基本设置
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: 我的小天地
  description: "分享生活，记录成长"
  keywords: [Blog, Portfolio, PaperMod]
  author: 你的名字
  DateFormat: "2006-01-02"
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  # 主页设置
  profileMode:
    enabled: false
    title: 我的博客
    subtitle: "欢迎访问我的博客"
    imageUrl: "#"
    imageWidth: 120
    imageHeight: 120
    imageTitle: profile image
    buttons:
      - name: 文章
        url: posts
      - name: 标签
        url: tags

  # 社交链接
  socialIcons:
    - name: github
      url: "https://github.com/yourusername"
    - name: twitter
      url: "https://twitter.com/yourusername"

# 菜单配置
menu:
  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 30
    - identifier: search
      name: 搜索
      url: /search/
      weight: 40